# Generated by Django 4.2.2 on 2024-01-01 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicos', '0002_remove_medicos_data_nascimento_medicos_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='usuario',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
