# Generated by Django 4.2.2 on 2023-06-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_idade_paciente_cpf_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paciente',
            new_name='Pacientes',
        ),
    ]
