# Generated by Django 4.2.2 on 2023-06-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_paciente_pacientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
