# Generated by Django 4.2.2 on 2023-06-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_pacientes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='email',
            field=models.CharField(default='NÃO INFORMADO', max_length=100),
        ),
    ]
