# Generated by Django 4.2.2 on 2023-06-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_pacientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
