# Generated by Django 4.2.2 on 2023-06-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_pacientes_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
