# Generated by Django 4.2.2 on 2024-01-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_alter_pacientes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
