# Generated by Django 4.2.2 on 2023-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamentos_id_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='oct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='olho_agendado',
            field=models.CharField(choices=[('esquerdo', 'Esquerdo'), ('direito', 'Direito'), ('ambos', 'Ambos')], default='Ambos', max_length=10),
        ),
    ]
