# Generated by Django 4.2.2 on 2023-06-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_agendamentos_oct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='observacao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
