# Generated by Django 4.2.2 on 2023-06-24 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('agendamentos', '0005_agendamentos_observacao_agendamentos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='id_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos'),
        ),
    ]
