# Generated by Django 4.2.2 on 2023-06-23 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('agendamentos', '0006_agendamentos_id_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='id_medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos'),
        ),
    ]
