# Generated by Django 4.2.2 on 2023-06-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_alter_agendamentos_id_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='diagnostico',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
