# Generated by Django 4.2.2 on 2023-06-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_agendamentos_atendido_alter_agendamentos_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='quantidade_aplicacoes_necessarias',
            field=models.IntegerField(default=0),
        ),
    ]
