# Generated by Django 4.2.2 on 2023-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_agendamentos_atendido_alter_agendamentos_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='aplicacao_atual',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='historico',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='numero_atualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='quantidade_aplicacoes_necessarias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='atendido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='status',
            field=models.CharField(default='não confirmado', max_length=20),
        ),
    ]
