# Generated by Django 4.2.2 on 2023-07-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_agendamentos_quantidade_aplicacoes_necessarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='aplicacao_atual',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
