# Generated by Django 4.2.2 on 2024-01-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_agendamentos_aplicacao_atual_agendamentos_historico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='id_medico',
        ),
    ]
