# Generated by Django 4.2.2 on 2024-01-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_remove_agendamentos_id_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='utlimo_atendimento',
            field=models.DateField(default='2023-12-01'),
            preserve_default=False,
        ),
    ]
