# Generated by Django 4.2.2 on 2023-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_alter_agendamentos_atendido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='status',
            field=models.CharField(choices=[('não confirmado', 'Não Confirmado'), ('cancelado', 'Cancelado'), ('remarcar', 'Remarcar'), ('concluido', 'Concluido')], default='não confirmado', max_length=20),
        ),
    ]
