# Generated by Django 4.2.2 on 2024-01-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_agendamentos_utlimo_atendimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamentos',
            old_name='utlimo_atendimento',
            new_name='ultimo_atendimento',
        ),
    ]
