# Generated by Django 4.2.2 on 2024-01-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_rename_utlimo_atendimento_agendamentos_ultimo_atendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='id_paciente',
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='cpf',
            field=models.CharField(default='', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='nome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='prontuario',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='telefone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
