# Generated by Django 4.2.2 on 2024-01-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_remove_agendamentos_id_paciente_agendamentos_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
