# Generated by Django 4.2.2 on 2024-01-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0014_alter_agendamentos_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='cartao_sus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='clinica',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='enfermaria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='leito',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='nome_mae',
            field=models.CharField(default='', max_length=100),
        ),
    ]
