# Generated by Django 4.2.2 on 2024-01-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0016_remove_agendamentos_id_procedimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='data_agendada',
            field=models.DateField(null=True),
        ),
    ]
