# Generated by Django 4.2.2 on 2024-01-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0017_alter_agendamentos_data_agendada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='ultimo_atendimento',
            field=models.DateField(null=True),
        ),
    ]
