# Generated by Django 4.2.2 on 2024-01-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0019_agendamentos_faltas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='quantidade_aplicacoes_necessarias',
            field=models.IntegerField(default=3),
        ),
    ]
