# Generated by Django 4.2.2 on 2024-01-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0020_alter_agendamentos_quantidade_aplicacoes_necessarias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='aplicacao_atual',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
