# Generated by Django 4.2.2 on 2024-01-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0021_alter_agendamentos_aplicacao_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='aplicacao_atual',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
