# Generated by Django 4.2.2 on 2024-01-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0022_alter_agendamentos_aplicacao_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='clinica',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='enfermaria',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='leito',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='nome_mae',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
