# Generated by Django 4.2.2 on 2024-01-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0023_alter_agendamentos_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='data_cadastro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='nivel_prioridade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
