from django.shortcuts import redirect
from django.urls import path
from . import views

urlpatterns = [
    path('cadastrarAgendamentos/', views.cadastrarAgendamentos,
         name="cadastrarAgendamentos"),
    path('gerarAgenda/', views.gerarAgenda, name="gerarAgenda"),
    path('gerarRelatorio/', views.gerarRelatorio, name="gerarRelatorio"),
    path('consultarAgendaDia/', views.consultarAgendaDia,
         name="consultarAgendaDia"),
    path('consultarAgendaDia/<str:filtro_agenda>/',
         views.consultarAgendaDia, name="consultarAgendaDiaFiltro"),
    path('imprimirAgenda/<str:data_selecionada>/',
         views.imprimirAgenda, name='imprimirAgenda'),
    path('confirmarAgendamentos/', views.confirmarAgendamentos,
         name='confirmarAgendamentos'),
    path('cadastrarPacientes/',
         lambda request: redirect('cadastrarPacientes', permanent=True)),
    path('cadastrarMedicos/',
         lambda request: redirect('cadastrarMedicos', permanent=True)),
    path('cadastrarAgendamentos/',
         lambda request: redirect('cadastrarAgendamentos', permanent=True)),
    path('cadastrarProcedimentos/',
         lambda request: redirect('cadastrarProcedimentos', permanent=True)),
    path('consultarAgendaDia/',
         lambda request: redirect('consultarAgendaDia', permanent=True)),
    path('home', lambda request: redirect('', permanent=True)),
    path('confirmarAtendimentos/', views.confirmarAtendimentos,
         name='confirmarAtendimentos'),
    path('consultarFilaEsperaPacientes/', views.consultarFilaEsperaPacientes,
         name='consultarFilaEsperaPacientes'),
    path('deletarPaciente/', views.deletarPaciente, name="deletarPaciente"),
    path('removerPacienteAgenda/', views.removerPacienteAgenda,
         name="removerPacienteAgenda"),
    path('removerPacienteConfirmarAgenda/', views.removerPacienteConfirmarAgenda,
         name="removerPacienteConfirmarAgenda"),
    path('agendarPaciente/', views.agendarPaciente, name="agendarPaciente"),
    path('atualizarCadastroAgendamento/', views.atualizarCadastroAgendamento,
         name="atualizarCadastroAgendamento"),
    path('listarPacientesDesinteressados/', views.listarPacientesDesinteressados,
         name="listarPacientesDesinteressados"),
    path('listarPacientesFinalizados/', views.listarPacientesFinalizados,
         name="listarPacientesFinalizados"),
]
